version: "3"

services:  
   bd:
      build:
        context: ./docker-postgres
        dockerfile: Dockerfile
      env_file: .env
      ports:
        - "5432:5432"

   backend:
      build:
        context: ./docker-flask
        dockerfile: Dockerfile
      env_file: .env
      ports:
        - "8080:8080"

   api:
      build:
        context: ./docker-shiny
        dockerfile: Dockerfile
      env_file: .env
      ports:
        - "3838:3838"
